### ISSUE TITLE
Concurrency definition question

### ISSUE THREAD

**Issue by tsenart** [codahale/usl4j#1]
Hello and thanks for this project (and many others!)

I'm struggling to understand the definition of concurrency. What should the request rate of each concurrent "driver" be? Is it possible to model concurrency as aggregate produced request rate? That would fit my tool Vegeta more closely, which spawns as many green threads as it needs to produce a defined request rate. That, of course, isn't the same as the throughput, which is the number of requests that were actually serviced per second.

Any help groking this is very much appreciated.

**Comment by codahale** [comment]
The definition of concurrency in the USL model is the number of requests in the “queue”: i.e. all in-flight requests at any point in time. If the system is not overloaded, this is however many concurrent threads are sending requests.

The number of requests per second that the system is processing is the throughput. In order to build a model, you will need to hold at least one of the parameters of Little’s Law (concurrency, throughput, latency) constant while recording the observed values of the other two. If your load generator varies concurrency, that’s fine as long as it a) holds throughput constant and b) tells you what the observed concurrency was.
